# Example mentions file for performing local testing.
# Copy this as 'mentions.yml' and amend to suit your needs.
# @local is taken as being the bot's username when running in test mode.

mention1:
  text: @local what is the time?
  user:
    id: 1
    name: Eric
    screen_name: eric
    
mention2:
  text: @local when is next tuesday?
  user:
    id: 2
    name: Billy
    screen_name: billy
  
mention3:
  text: @local are you stupid?
  user:
    id: 1
    name: Eric
    screen_name: eric
